FROM node:10.16.3-stretch as builder

WORKDIR /root/package
COPY package.json package-lock.json ./
RUN npm install
ENV REACT_SET_APP_AUTH=passcode
COPY . /root/package/
RUN npm run build

FROM nginx
COPY --from=builder /root/package/build/ /usr/share/nginx/html/
COPY ./cloud/nginx.conf /etc/nginx/nginx.conf
COPY ./cloud/default.conf /etc/nginx/conf.d/default.conf
