// UserInfoOverlayRegistry Constants
export enum USER_INFO_OVERLAY_TYPES {
  USER_AND_CONNECTION_INFO = 'USER_AND_CONNECTION_INFO',
  VIDEO_AND_AUDIO_INFO = 'VIDEO_AND_AUDIO_INFO',
  PIN_ICON = 'PIN_ICON',
  NETWORK_QUALITY_LEVEL = 'NETWORK_QUALITY_LEVEL',
}
